# Wazuh App Copyright (C) 2018 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: wazuh/wazuh:3.6.1_6.4.2
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
#      - "1516:1516"
    networks:
        - docker_elk
    volumes:
      - /var/containers/wazuh/var/ossec/data:/var/ossec/data:Z
      - /var/containers/wazuh/etc/postfix:/etc/postfix:Z
      - /var/containers/wazuh/etc/filebeat:/etc/filebeat
      - /var/containers/wazuh/wazuh-config-mount/etc/ossec.conf:/wazuh-config-mount/etc/ossec.conf:Z
    depends_on:
      - logstash
  logstash:
    image: logstash:6.2.1
    hostname: logstash
    restart: always
    volumes:
      - /var/containers/logstash/pipeline/:/usr/share/logstash/pipeline/bin
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
#      - "5044:5044"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
  filebeat:
    image: filebeat:6.2.1
    hostname: filebeat
    restart: always
    volumes:
      - /var/containers/logstash/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/containers/logstash/filebeat/prospectors.d:/usr/share/filebeat/prospectors.d
      - /var/containers/logstash/filebeat/data.log:/var/log/data.log
    links:
      - logstash:logstash
    ports:
      - "5000:5000"
      - "5044:5044"
    networks:
      - docker_elk
    depends_on:
      - logstash
  elasticsearch:
    image: elasticsearch:5.2.2
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch -E node.name="node-1" -E cluster.name="wazuh" -E network.host=0.0.0.0
    environment:
#      - node.name=node-1
#      - cluster.name=wazuh
#      - network.host=0.0.0.0
#      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - /var/containers/wazuh/usr/share/elasticsearch/data:/usr/share/elasticsearch/data:Z
    networks:
        - docker_elk
  kibana:
    image: wazuh/wazuh-kibana:3.6.1_6.4.2
    hostname: kibana
    restart: always
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
  nginx:
    image: wazuh/wazuh-nginx:3.6.1_6.4.2
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/containers/wazuh/etc/nginx/conf.d:/etc/nginx/conf.d:Z
    networks:
      - docker_elk
    depends_on:
      - kibana
    links:
      - kibana:kibana

networks:
  docker_elk:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24