version: '2'

services:

  elasticsearch:
    image: elasticsearch:5.2.2
    hostname: elasticsearch
#    restart: always
    volumes:
      - /var/containers/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /var/containers/elasticsearch/usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.1
    hostname: logstash
    restart: always
    volumes:
      - /var/containers/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - /var/containers/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    links:
      - elasticsearch:elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    hostname: kibana
    restart: always
    volumes:
      - /var/containers/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch

networks:

  elk:
    driver: bridge
